[build]
  base = "src"              # Specify the directory where your React app source code resides
  publish = "public"        # Specify the directory where the optimized build will be

  command = "CI='' npm run build" # The command to build your React app

[build.environment]
  # You can set environment variables if needed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
